### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [yuanyxh/u-android-native-plugin#1]
请问大佬,这个camera 和 notify 的插件如何导入到 uni-app 中使用了

**Comment by yuanyxh** [comment]
说的很详细了，如果你没有对应的基础可以先看一下 Android Studio 的使用方式，大概步骤是：

1. 导入对应的 module 到 as 中你的项目里，比如导入 camera 就导入这个项目的 camera 文件夹
2. 在你的编译配置里引入这个 module 的依赖并编译
3. 在 uniapp 代码里导入使用

**Comment by shenhaoguangDayDayUp** [comment]
> 说的很详细了，如果你没有对应的基础可以先看一下 Android Studio 的使用方式，大概步骤是：
> 
> 1. 导入对应的 module 到 as 中你的项目里，比如导入 camera 就导入这个项目的 camera 文件夹
> 2. 在你的编译配置里引入这个 module 的依赖并编译
> 3. 在 uniapp 代码里导入使用

谢谢大佬,我试试先
